pipeline:
    name: Helm Quickstart
    identifier: Helm_Quickstart
    allowStageExecutions: false
    projectIdentifier: suranbootcamp
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: nginx-helm-suran
              identifier: nginxhelmsuran
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: nginxhelmsuran
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: nginxhelmsuran
                                        type: HelmChart
                                        spec:
                                            store:
                                                type: Http
                                                spec:
                                                    connectorRef: account.helmbitnami
                                            chartName: nginx
                                            chartVersion: ""
                                            helmVersion: V3
                                            skipResourceVersioning: false
                  infrastructure:
                      environmentRef: suranhelmenv
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.bootcampgkecluster
                              namespace: internalbootcamp-suran
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
