pipeline:
    name: suran-pipeline-canary
    identifier: suranpipelinecanary
    allowStageExecutions: false
    projectIdentifier: suranbootcamp
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: suran-deploy-stage
              identifier: surandeploystage
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: suranservice
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: suran_values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.EliGit
                                                    gitFetchType: Branch
                                                    paths:
                                                        - values.yml
                                                    repoName: ngfundamentals
                                                    branch: main
                                  - manifest:
                                        identifier: suranmanifests
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.EliGit
                                                    gitFetchType: Branch
                                                    paths:
                                                        - templates/app-deployment.yml
                                                        - templates/namespace.yml
                                                    repoName: ngfundamentals
                                                    branch: main
                                            skipResourceVersioning: false
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: account.bootcampdockerhub
                                          imagePath: library/nginx
                                          tag: <+input>
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: suranenvironment
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.bootcampgkecluster
                              namespace: internalbootcamp-suran
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: K8sCanaryDeploy
                                name: deploy canary
                                identifier: deploy_canary
                                spec:
                                    skipDryRun: false
                                    instanceSelection:
                                        type: Count
                                        spec:
                                            count: 1
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: sleep
                                identifier: sleep
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: sleep 30
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                type: K8sCanaryDelete
                                name: delete canary
                                identifier: delete_canary
                                spec:
                                    skipDryRun: false
                                timeout: 10m
                          - step:
                                type: K8sRollingDeploy
                                name: rollout to env
                                identifier: rollout_to_env
                                spec:
                                    skipDryRun: false
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
              variables: []
